version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/rithm_platform
      - SESSION_SECRET=your_secure_session_secret_here
    depends_on:
      - db
    volumes:
      - ./data:/app/data
      - ./models:/app/models

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=rithm_platform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: