services:
  - type: web
    name: ml-platform
    env: node
    plan: starter
    buildCommand: |
      # Install Python and ML dependencies
      pip3 install -r python-requirements.txt
      # Build Node.js application
      npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ml-platform-db
          property: connectionString
    healthCheckPath: /health
    
databases:
  - name: ml-platform-db
    plan: starter
