services:
  - type: web
    name: rithm-ml-platform
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: starter
    branch: main
    buildCommand: |
      npm ci --production=false
      node build-production.js
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: rithm-storage
      mountPath: /app/storage
      sizeGB: 10
    
  - type: pserv
    name: rithm-postgres
    env: docker
    dockerCommand: |
      docker run -p 5432:5432 \
        -e POSTGRES_DB=rithm_ml_platform \
        -e POSTGRES_USER=admin \
        -e POSTGRES_PASSWORD=secure_password_2024 \
        postgres:15-alpine
    plan: starter
    region: oregon
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 20
    envVars:
      - key: POSTGRES_DB
        value: rithm_ml_platform
      - key: POSTGRES_USER
        value: admin
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: rithm-postgres
          property: connectionString

databases:
  - name: rithm-postgres
    databaseName: rithm_ml_platform
    user: admin
    plan: starter
    region: oregon